# Extended Test Suite for BayesianDoubleML.jl
# Run manually: julia --project=. test/extended/runtests.jl
#
# These tests are not run in CI but can be executed for:
# - Release testing
# - Performance benchmarking
# - AD backend comparisons
# - Large dataset validation
# - Comprehensive validation
#
# NOTE: The UnifiedVI/SimpleVI extended tests (ad_backends_extended.jl,
# subsampling_extended.jl) were archived to
# src/.archive/removed_unified_simple_2026-09-05/ when UnifiedVI/SimpleVI
# support was removed. There are currently no extended tests.

using SafeTestsets

println("\n========================================")
println("BayesianDoubleML.jl Extended Test Suite")
println("========================================\n")

println("No extended tests currently defined.")

println("\n=== Bayes-DR Reference Tests ===")
println("Testing: tiny binary and continuous fixtures generated by DoublyRobustHD\n")

@safetestset "Bayes-DR R Reference" begin
    include("bayes_dr_reference.jl")
end

println("\n========================================")
println("Extended Tests Complete")
println("========================================")
